id = "the-code-fixer-23 asciidoc"
name = "The Code Fixer AsciiDoc"
version = "1.0.0"
schema_version = 1
authors = ["Shelton Louis <louisshelton0@gmail.com>"]
description = "Support for AsciiDoc syntax"
repository = "https://github.com/louiss0/zed-language-ext-asciidoc"
icon = "icon.svg"
categories = ["Programming Languages", "Documentation"]
keywords = [
    "asciidoc",
    "adoc",
    "asciidoctor",
    "markup",
    "documentation",
    "syntax highlighting",
]
license = "MIT"
bugs = { url = "https://github.com/louiss0/zed-language-ext-asciidoc/issues" }

[grammars.asciidoc]
repository = "https://github.com/cpkio/tree-sitter-asciidoc.git"
commit = "95ac471564c5cfcc8cbe940bbb4cb6aafa24f395"
